---

escalation_policies:

  'DevOps team escalation policy':
    description: 'DevOps team escalation policy'
    teams:
      - 'DevOps'
    num_loops: 5
    rules:
    - escalation_delay_in_minutes: 10
      targets:
      - type: 'schedule_reference'
        target_name: 'DevOps team in-hours schedule'
      - type: 'user_reference'
        target_name: 'Bob Smith'
    - escalation_delay_in_minutes: 5
      targets:
      - type: 'user_reference'
        target_name: 'Bob Smith'

  'Engineering team escalation policy':
    description: 'Engineering team escalation policy'
    teams:
      - 'Engineering'
    num_loops: 2
    rules:
    - escalation_delay_in_minutes: 20
      targets:
      - type: 'schedule_reference'
        target_name: 'DevOps team in-hours schedule'
    - escalation_delay_in_minutes: 5
      targets:
      - type: 'user_reference'
        target_name: 'Barry Bethel'
