---

schedules:
  'DevOps team in-hours schedule':
    time_zone: 'Europe/London'
    description: 'In-hours rota for the DevOps team'
    teams:
      - 'Engineering'
      - 'DevOps'
    overflow: false
    layers:
    - name: 'Layer 1'
      start: '2023-07-24T20:00:00-00:00'
      rotation_virtual_start: '2023-07-25T10:00:00Z'
      rotation_turn_length_seconds: 604800
      restrictions:
      - type: 'weekly_restriction'
        start_day_of_week: 1
        start_time_of_day: '09:00:00'
        duration_seconds: 28800
      - type: 'weekly_restriction'
        start_day_of_week: 2
        start_time_of_day: '09:00:00'
        duration_seconds: 28800
      - type: 'weekly_restriction'
        start_day_of_week: 3
        start_time_of_day: '09:00:00'
        duration_seconds: 28800
      - type: 'weekly_restriction'
        start_day_of_week: 4
        start_time_of_day: '09:00:00'
        duration_seconds: 28800
      - type: 'weekly_restriction'
        start_day_of_week: 5
        start_time_of_day: '09:00:00'
        duration_seconds: 28800
      users:
        - 'Barry Bethel'
        - 'Bob Smith'
